/**
 * @fileoverview gRPC-Web generated client stub for capstone
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.21.12
// source: ground.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var values_pb = require('./values_pb.js')
const proto = {};
proto.capstone = require('./ground_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.capstone.GroundStationClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.capstone.GroundStationPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.capstone.ValueRequest,
 *   !proto.capstone.Value>}
 */
const methodDescriptor_GroundStation_GetValue = new grpc.web.MethodDescriptor(
  '/capstone.GroundStation/GetValue',
  grpc.web.MethodType.UNARY,
  proto.capstone.ValueRequest,
  values_pb.Value,
  /**
   * @param {!proto.capstone.ValueRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  values_pb.Value.deserializeBinary
);


/**
 * @param {!proto.capstone.ValueRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.capstone.Value)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.capstone.Value>|undefined}
 *     The XHR Node Readable Stream
 */
proto.capstone.GroundStationClient.prototype.getValue =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/capstone.GroundStation/GetValue',
      request,
      metadata || {},
      methodDescriptor_GroundStation_GetValue,
      callback);
};


/**
 * @param {!proto.capstone.ValueRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.capstone.Value>}
 *     Promise that resolves to the response
 */
proto.capstone.GroundStationPromiseClient.prototype.getValue =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/capstone.GroundStation/GetValue',
      request,
      metadata || {},
      methodDescriptor_GroundStation_GetValue);
};


module.exports = proto.capstone;

